ALTER TABLE preference ADD COLUMN email_limit INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE preference ADD COLUMN email_sent INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE preference ADD COLUMN email_sent_timestamp DATETIME;
