ALTER TABLE smoke_report DROP COLUMN format;
ALTER TABLE smoke_report DROP COLUMN html_file;
ALTER TABLE smoke_report ADD COLUMN todo_pass INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE project ADD COLUMN enable_rss BOOL NOT NULL DEFAULT 1;
