=head1 SMOLDER CHANGES

=head2 1.21

=over

=item * Added F<docs/porting.pod> and fixed bad link in F<docs/ops_install.pod> - M. Peters

=item * Fixed build issue where Carp::Clan was hanging - M. Peters

=item * Fixed build issue on Mac OSX where we were looking for F<.so> files instead of F<.dynlib> - Michael Schwern, M. Peters

=item * Fixed test of MySQL isolation level to accept C<READ-COMMITTED> or stricter - Sam Villain

=back

=head2 1.2

=over

=item * Removed F<smolder_prove>. You can now get the new TAP archive format by using L<TAP::Parser>'s C<runtests --archive>.

=item * Change the UI for assigning developers to projects to allow for larger lists of groups and developers - M. Peters

=item * Upgraded 3rd party JavaScript libraries (prototype, scriptaculous) and remove unnecssary JS and CSS files - M. Peters

=item * Fixed bug where emails weren't being sent out. - M. Peters

=item * SMTPHost config directive is now optional and Smolder will use the local sendmail program if it's not provided. - M. Peters

=item * Now using L<TAP::Harness::Archive> as the suggested method of creating the TAP archive. Also use it for manipulating them. - M. Peters

=back

=head2 1.1

=over

=item * Now using straight TAP (bundled in an archive file) instead of the custom XML/YAML thing we were using before. - M. Peters

=item * Added Atom feeds that can be enabled per project. - M. Peters

=item * Updated various component source modules and projects. - M. Peters

=item * Removed swish-e and mod_auth_tkt since they weren't essential to the functioning of smolder, but added a lot of size. - M. Peters

=item * Allow F<smolder.conf> to be located in various places, not just F<$SMOLDER_ROOT/conf/smolder>. We now look first at F<$SMOLDER_CONF>, then in F<$SMOLDER_ROOT/conf>, F</usr/local/smolder/conf> and then F</etc/smolder>. - M. Peters

=item * Added "Show All Details" link to test reports. Will suck browser resources if used on large test reports, but should be find on smaller ones - M. Peters

=item * Fixed upgrades to now use appropriate sql file depending on the running DBPlatform. - M. Peters

=item * Updated various images. - M. Peters

=item * Added F<bin/smolder_update_smoke_html> so that you can regenerate the HTML of the smoke reports after a template change. - M. Peters

=back

=head2 1.02

=over

=item * Better tolerance of email failures, allowing the action to proceed and warnings to be sent to the log (and user when appropriate) - M. Peters

=item * Added C<--not-perl> option to F<bin/smolder_prove> so that it will simply exec files without treating them like Perl scripts. - M. Peters

=item * Fixed bug when building with C<--no-mysql> on a system that doesnt have MySQL installed - Trushar Zaveri and M. Peters

=item * Fixed bug to allow anonymous access to test file details for public projects - M. Peters

=head2 1.01

=over

=item * Fixed bug with uploading YAML files instead of XML - M. Peters

=item * Disable form inputs when AJAXified forms are submitting, then re-enable them on request completion - M. Peters

=item * Minor bug fixes with CRUD UI's - M. Peters

=item * Changed the validation messages to use the same message stack as other messages instead of being inlined. - M. Peters

=item * Better display of test descriptions and diagnostic messages in HTML results matrix. - M. Peters

=back

=head2 1.00

=over

=item * Added dynamic HTML TAP Matrix views - M. Peters

=item * Fixed some navigation issues with paged results of smoke reports when using categories. - M. Peters

=item * Removed Swish-e and searchable docs from Smolder. We'll have this someday on the website (when we get one). - M. Peters

=item * Fixed some build/install issues for FreeBSD and MySQL - M. Peters

=item * Added mising Method::Alias module - Sam Tregar

=item * HTML escape test data in the TAP Matrix - M. Peters

=back

=head2 0.3 (1.0 RC1)

=over

=item * Mark tests that have files that exit with a non-zero status that use 'no_plan' to be marked as failing - M. Peters

=item * Allow anonymous smoke tests added to public projects - M. Peters

=item * Added public projects - M. Peters

=item * Upgrading to Apache 1.3.36 - M. Peters

=item * Auto-purging of old compressed XML files by ProjectFullReportsMax config directive - M. Peters

=item * Better caching headers for static files - M. Peters

=item * Fixed building of SQLite on some platforms - Mark Stosberg

=item * Searchable HTML versions of docs - M. Peters

=item * Fixing graph generation bug when using SQLite - Sam Tregar

=item * Compressed XML storage and acceptance during upload - M. Peters, Sam Tregar

=item * Runtime errors sometimes being lost - Sam Tregar, M. Peters

=item * Removed un-used mod_ssl sources and build - M. Peters

=back

=head2 0.2

=over 

=item * Turn on mod_auth_tkt for all dynamic requests so that Apache auth stages are run and valid credentials produced - M. Peters

=item * Added smolder_prove, to run any normal Perl tests for smolder - M. Peters

=item * Send the port number in URLs in emails - Sam Tregar

=item * Skip the authinfo test if Apache is not running - Sam Tregar

=item * Added missing modules to src (XML::Parser, XML::SAX::Expat, Exception::Class and Exception::Class::TryCatch) - Sam Tregar

=item * Using a smaller number of Apache children and Apache::SizeLimit to limit any memory hogging - M. Peters

=item * Added built-in SQLite support - (M. Peters, Mark Stosberg) 

=item * Added multi-db support via Smolder::DBPlatform - M. Peters

=item * Upgraded DBI to 1.50 - M. Peters

=item * Added notification to the user of failed AJAX requests - M. Peters

=back

=head2 0.1

=over

=item * Overhaul and review of upgrade system - M. Peters

=item * Project admins can control when the project graph starts by default - M. Peters

=item * Can now view progress graph by platform and architecture - M. Peters

=item * Overhaul of Admin Developer/Project CRUDs to keep everything on one AJAXified screen - M. Peters

=back

=head2 0.04 (March 13, 2006)

=over

=item * Added ability to see just a single report by id; Smoke report emails now link to single reports - M. Peters

=item * Added logging to Apache::Log via Log::Dispatch and CGI::Application::Plugin::LogDispatch - M. Peters

=item * Fixed smolder_backup and smolder_install to work together and allow installation from a backup - M. Peters

=item * Reviewed all templates and fixed potential XSS issue with non escaped data - M. Peters

=item * Added top-level Makefile as a shortcut to various actions/scripts - M. Peters

=item * Explicitly set Expires headers for CSS/JS/Image to improve caching - M. Peters

=item * Run tests as User/Group if we can - M. Peters

=item * Check for libgd on install - M. Peters

=item * FreeBSD control scripts moved from /etc/rc.d to /usr/local/etc/rc.d.  Currently there is no automatic migration of scripts previously installed in /etc/rc.d by smolder. - Mark Stosberg

=back

=head2 0.03 (March 06, 2006)

=over

=item * Added more missing Perl modules to src/ directory - M. Peters

=item * Allow smolder_createdb to use MySQL root passwords with spaces - Matisse Enzer

=item * Add "--dry-run" option to smolder_createdb. -Mark Stosberg 

=back

=head2 0.02 (March 05, 2006)

=over

=item * Fixed building of GD.pm on FreeBSD - Mark Stosberg

=item * Added missing Perl modules to src/ directory - M. Peters

=back

=head2 0.01 (March 04, 2006)

=over

=item * Initial public release

=back
