=head1 SMOLDER CHANGES

=head2

=over

=item * Run tests as User/Group if we can - Michael Peters

=item * Check for libgd on install - Michael Peters

=item * FreeBSD control scripts moved from /etc/rc.d to /usr/local/etc/rc.d.  Currently there is no automatic migration of scripts previously installed in /etc/rc.d by smolder. - Mark Stosberg

=back

=head2 0.03 (March 06, 2006)

=over

=item * Added more missing Perl modules to src/ directory - Michael Peters

=item * Allow smolder_createdb to use MySQL root passwords with spaces - Matisse Enzer

=item * Add "--dry-run" option to smolder_createdb. -Mark Stosberg 

=back

=head2 0.02 (March 05, 2006)

=over

=item * Fixed building of GD.pm on FreeBSD - Mark Stosberg

=item * Added missing Perl modules to src/ directory - Michael Peters

=back

=head2 0.01 (March 04, 2006)

=over

=item * Initial public release

=back
