=head1 SMOLDER CHANGES

=head2 0.05

=over

=item * Can now view progress graph by platform and architecture - M. Peters

=item * Overhaul of Admin Developer/Project CRUDs to keep everything on one AJAXified screen - M. Peters

=back

=head2 0.04 (March 13, 2006)

=over

=item * Added ability to see just a single report by id; Smoke report emails now link to single reports - M. Peters

=item * Added logging to Apache::Log via Log::Dispatch and CGI::Application::Plugin::LogDispatch - M. Peters

=item * Fixed smolder_backup and smolder_install to work together and allow installation from a backup - M. Peters

=item * Reviewed all templates and fixed potential XSS issue with non escaped data - M. Peters

=item * Added top-level Makefile as a shortcut to various actions/scripts - M. Peters

=item * Explicitly set Expires headers for CSS/JS/Image to improve caching - M. Peters

=item * Run tests as User/Group if we can - M. Peters

=item * Check for libgd on install - M. Peters

=item * FreeBSD control scripts moved from /etc/rc.d to /usr/local/etc/rc.d.  Currently there is no automatic migration of scripts previously installed in /etc/rc.d by smolder. - Mark Stosberg

=back

=head2 0.03 (March 06, 2006)

=over

=item * Added more missing Perl modules to src/ directory - M. Peters

=item * Allow smolder_createdb to use MySQL root passwords with spaces - Matisse Enzer

=item * Add "--dry-run" option to smolder_createdb. -Mark Stosberg 

=back

=head2 0.02 (March 05, 2006)

=over

=item * Fixed building of GD.pm on FreeBSD - Mark Stosberg

=item * Added missing Perl modules to src/ directory - M. Peters

=back

=head2 0.01 (March 04, 2006)

=over

=item * Initial public release

=back
