=head1 Releasing Smolder

This document describes how to make a new release of Smolder.

=head2 Pre-Release Checklist

=over

=item 1

Make sure all changes are committed to SVN.

=item 2

Verify that an upgrade module has been created for this release, if necessary

=item 3

Update $VERSION in Smolder.pm and commit.

=back

=head2 Building the Source Distribution

=over

=item 1

Make a clean checkout of Smolder:

=item 2

Run smolder_makedist:

  bin/smolder_makedist

This will create 'smolder-$VERSION-src.tar.gz'.

=item 3

Upload the file to SourceForge and post an announcement to the Smolder
and related (CGI::Application, perl-qa, etc) mailing lists.

=back

=head2 Building Binary Distributions

On each supported platform perform these steps:

=over

=item 1

Download the source distribution and untar it.

=item 2

Run smolder_build, supplying the plaform name if necessary:

  bin/smolder_build

=item 3

Run smolder_makedist:

  bin/smolder_makedist

This will create 'smolder-$VERSION-$PLATFORM-$PERL-$ARCH.tar.gz', which
is a binary distribution of Smolder.

=item 4

Upload the file to SourceForge and post an announcement to the Smolder
mailing lists.

=back
