=head1 TODO

=head2 FOR 2.0

=over

=item *

Graphing of execution times over time. When combined with a graph of the
number of tests run it can show when performance regressions have entered.

=item * 

Tracking of individual tests. This would provide a view that let's
the user see when each test was added and maybe how it has faired 
over time. MediaWiki has an example of this:

    * HTML nested bullet list, open tags (bug 5497)    [Has never passed]
    * HTML nested ordered list, open tags (bug 5497)   [Has never passed]
    * Fuzz testing: image with bogus manual thumbnail  [Introduced
      between 08-Apr-2007 07:15:22, 1.10alpha (r21099) and 25-Apr-2007
      07:15:46, 1.10alpha]

=item *

Make it easier for custom installation on existing Apache or maybe even
make a lite version that uses HTTP::Server::Simple?

=over

=item Work better under Apache2/mod_perl2 (possibly CGI?)

=item Create a CPAN bundle

=back

=item *

Add preference to just get plain-text emails

=item *

Create an interface for comparing 2 sets of reports for the same project. 
Possibly similar to the way you select data for graphing.

=item *

Replace image based graphs with C<< <canvas> >> ones (using Plotr?)

=item *

Create a full search system of smoke reports, not just a listing
by most recent. This would allow for searching based on project,
status, category, etc.

=item *

Support TAP tags (tags made with Test::Description::Tagged)

=item *

Better message stack that works arcoss sessions.

=item *

Precompile all templates at startup (speeds it up and increases shared memory)

=item *

Rendering in other browsers besides FF and KHTML

=item *

Import/export projects (similar to backup and install from backup but by project)

=item *

Add paging to other listing pages admin_developers/admin_projects, etc (or add datagrid?)

=item *

Add help tooltips where appropriate

=item *

Allow smolder_smoke_signal to use the Smolder modules directly if it's on the same machine.

=back

=head2 BEYOND

=over

=item *

Make sure it builds/runs/installs on as many *nix platforms as possible

=item *

Add coverage reports (related to smoke tests?)

=item *

Add benchmark gathering?

=item *

Make SQLite the default instead of MySQL?

=back
    




