=head1 TODO

=head2 FOR 1.0

=over

=item *

Review upgrade procedure to make sure it's working completely

=back

=head2 FOR 2.0

=over

=item *

More dynamic, AJAX HTML Matrix for test reports. Should reduce bandwidth
and make it quicker for the user to see what he wants to see.

=item *

Add support for plain TAP

=item *

Precompile all templates at startup (speeds it up and increases shared memory)

=item *

Rendering in other browsers besides FF and KHTML

=item *

Import/export projects (similar to backup and install from backup but by project)

=item *

Add paging to other listing pages admin_developers/admin_projects, etc (or add datagrid?)

=item *

Capture STDERR and associate with test files 

needs changes to Test::Builder

=item *

Add help tooltips where appropriate

=back

=head2 BEYOND

=over

=item *

Make sure it builds/runs/installs on as many *nix platforms as possible

=item *

Optional logging of critical problems to email?

=item *

Built-in SSL support?

=item *

Add some benchmarks so we can see how things perform as changes are made

=item *

Add CSV download option for tests (for projects?)    

=item *

Look at using an XML schema that isn't so tied to the internal representation of Test::TAP::Model and Test::Harness::Straps

=item *

Add coverage reports (related to smoke tests?)

=item *

Add benchmark gathering?

=item *

Add RSS feeds per project

=item *

Look at making skinning easier so that organizations can brand it

=item *

Verify support for non AJAX browsers

=item *

Support for other databases (need developers to support them)

=over

=item *

PostgreSQL

=back

=back
    




