=head1 TODO

=head2 FOR 0.1

=over

=item * tests should switch to the smolder user if possible

=item * fix some POD style issues leftover from Krang

=item * top level Makefile for common tasks (make test, make db, etc)

=item * make sure backup works (and install from backup)

=item * Add support for plain TAP

=item * document all classes

Controller classes

Document all run modes (templates used, etc)

=item * Add a decent logging mechanism (Log::Dispatch and C::A::P::LogDispatch)

=item * Precompile all templates at startup

=item * escape all data that is displayed that could have come from users to prevent XSS

=item * view graphs by platform/architecture

=item * rendering in other browsers besides FF

=item * Add customization of graph start/end date for graphs to Project Admin Settings

=back

=head2 FOR 0.2

=over

=item * searchable HTML docs

=item * built-in SQLite support

=item * import/export projects (all data and reports)

=item * Add paging to other listing pages admin_developers/admin_projects, etc (possibly add sortable table as well)

=item * Add 'public' projects

=over

=item * allow anonymous test reports from public (add extra 'anonymous' user?)

=item * show listing on front page

=item * show test reports/graphs to the public

=back

=back

=head2 FOR 1.0

=item * make sure it builds/runs/installs on as many *nix platforms as possible

=item * capture STDERR and associate with test files 

needs changes to Test::Harness::Straps and Test::TAP::Model

=item * add help tooltips where appropriate

=over

=back

=head2 BEYOND

=over

=item * built-in SSL support?

=item * add some benchmarks so we can see how things perform as changes are made

=item * add CSV download option for tests (for projects?)    

=item * look at using an XML schema that isn't so tied to the internal representation of Test::TAP::Model and Test::Harness::Straps

=item * add coverage reports (related to smoke tests?)

=item * add benchmark gathering?

=item * add RSS feeds per project

=item * look at making skinning easier so that organizations can brand it

=item * verify and test support for non AJAX browsers

=item * support for other databases (need developers to support them)

=over

=item * PostgreSQL

=back

=back
    




